<a href="https://colab.research.google.com/github/Diggi14/project_Property2/blob/main/feature_extraction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!git clone https://github.com/Diggi14/project_Property2.git

Cloning into 'project_Property2'...
remote: Enumerating objects: 103, done.
remote: Counting objects: 100% (103/103), done.
remote: Compressing objects: 100% (101/101), done.
remote: Total 103 (delta 55), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (103/103), 6.03 MiB | 2.59 MiB/s, done.
Resolving deltas: 100% (55/55), done.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [7]:
df=pd.read_csv('/content/project_Property2/cleaned_data4.csv')

In [8]:
df.head(3)

,Unnamed: 0,PREFERENCE,PROPERTY_TYPE,BEDROOM_NUM,BATHROOM_NUM,BALCONY_NUM,PRICE_PER_UNIT_AREA,FURNISH,AGE,FLOOR_NUM,SUPERBUILTUP_SQFT,PRICE,SOCIETY_NAME,LOCALITY_WO_CITY,FEATURES_LIST,stories,nearby_facilities,total_facilities,furnishing_type
0,0,S,Residential Apartment,4.0,4.0,4.0,8766.0,Semi-furnished,5-10,14.0,3434.0,2.63,Alpha Corp GurgaonOne 84,Sector 84,"['Intercom Facility', 'Lift(s)', 'Water purifi...",single,"['Bank/ATM', 'Park', 'School/College', 'Hospit...",4,0
1,1,S,Residential Apartment,4.0,4.0,3.0,21176.0,Semi-furnished,1-5,7.0,2870.0,3.60,DLF The Ultima,Sector 81,"['Security / Fire Alarm', 'Feng Shui / Vaastu ...",single,"['Railway', 'School/College', 'Metro', 'Hospit...",5,0
2,2,S,Residential Apartment,3.0,3.0,3.0,13740.0,Semi-furnished,1-5,14.0,2802.0,3.85,Experion Windchants,Sector 112,"['Power Back-up', 'Feng Shui / Vaastu Complian...",single,"['Railway', 'School/College', 'Hospital', 'Air...",4,0

In [9]:
df.drop(['Unnamed: 0','SOCIETY_NAME','FEATURES_LIST','nearby_facilities'],inplace=True,axis=1)

In [10]:
df.head(4)

,PREFERENCE,PROPERTY_TYPE,BEDROOM_NUM,BATHROOM_NUM,BALCONY_NUM,PRICE_PER_UNIT_AREA,FURNISH,AGE,FLOOR_NUM,SUPERBUILTUP_SQFT,PRICE,LOCALITY_WO_CITY,stories,total_facilities,furnishing_type
0,S,Residential Apartment,4.0,4.0,4.0,8766.0,Semi-furnished,5-10,14.0,3434.0,2.63,Sector 84,single,4,0
1,S,Residential Apartment,4.0,4.0,3.0,21176.0,Semi-furnished,1-5,7.0,2870.0,3.60,Sector 81,single,5,0
2,S,Residential Apartment,3.0,3.0,3.0,13740.0,Semi-furnished,1-5,14.0,2802.0,3.85,Sector 112,single,4,0
3,S,Residential Apartment,3.0,4.0,4.0,8515.0,Semi-furnished,1-5,4.0,2290.0,1.95,Sector 104,single,6,0

In [11]:
df.duplicated().sum()

np.int64(33)

In [12]:
df.drop_duplicates(inplace=True)

In [13]:
df['FLOOR_NUM'].describe()

count    9346.000000
mean        6.801305
std         6.210952
min        -1.000000
25%         2.000000
50%         5.000000
75%        10.000000
max        48.000000
Name: FLOOR_NUM, dtype: float64

In [14]:
def categotize_floor(val):
  if(val<=2):
    return 'low'
  elif(val<=10):
    return 'mid'
  else:
    return 'high'

In [15]:
df['FLOOR_NUM']=df['FLOOR_NUM'].apply(categotize_floor)

In [16]:
df.head(2)

,PREFERENCE,PROPERTY_TYPE,BEDROOM_NUM,BATHROOM_NUM,BALCONY_NUM,PRICE_PER_UNIT_AREA,FURNISH,AGE,FLOOR_NUM,SUPERBUILTUP_SQFT,PRICE,LOCALITY_WO_CITY,stories,total_facilities,furnishing_type
0,S,Residential Apartment,4.0,4.0,4.0,8766.0,Semi-furnished,5-10,high,3434.0,2.63,Sector 84,single,4,0
1,S,Residential Apartment,4.0,4.0,3.0,21176.0,Semi-furnished,1-5,mid,2870.0,3.60,Sector 81,single,5,0

In [17]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df_encode=df.copy()
col=df.select_dtypes(include='object').columns
for i in col:
  df_encode[i]=le.fit_transform(df_encode[i])

In [18]:
df_encode.head(2)

,PREFERENCE,PROPERTY_TYPE,BEDROOM_NUM,BATHROOM_NUM,BALCONY_NUM,PRICE_PER_UNIT_AREA,FURNISH,AGE,FLOOR_NUM,SUPERBUILTUP_SQFT,PRICE,LOCALITY_WO_CITY,stories,total_facilities,furnishing_type
0,1,2,4.0,4.0,4.0,8766.0,1,3,0,3434.0,2.63,137,1,4,0
1,1,2,4.0,4.0,3.0,21176.0,1,1,2,2870.0,3.60,133,1,5,0

In [19]:
corr1=df_encode.corr()['PRICE'].sort_values(ascending=False).iloc[1:].reset_index().rename(columns={'index':'feature','PRICE':'correlation'})

In [20]:
corr1

                feature  correlation
0     SUPERBUILTUP_SQFT     0.758833
1   PRICE_PER_UNIT_AREA     0.745698
2          BATHROOM_NUM     0.594106
3           BEDROOM_NUM     0.528255
4           BALCONY_NUM     0.207071
5      total_facilities     0.078267
6            PREFERENCE     0.010351
7                   AGE    -0.000196
8       furnishing_type    -0.061069
9             FLOOR_NUM    -0.105686
10              FURNISH    -0.152350
11        PROPERTY_TYPE    -0.165984
12     LOCALITY_WO_CITY    -0.217495
13              stories    -0.251982

In [21]:
x=df_encode.drop('PRICE',axis=1)
y=df_encode['PRICE']

In [22]:
from sklearn.ensemble import RandomForestRegressor
rf=RandomForestRegressor()
rf.fit(x,y)
feat_imp=pd.DataFrame({'feature':x.columns,'importance':rf.feature_importances_}).sort_values(by='importance',ascending=False)

In [23]:
feat_imp

                feature  importance
9     SUPERBUILTUP_SQFT    0.568510
5   PRICE_PER_UNIT_AREA    0.416790
10     LOCALITY_WO_CITY    0.005608
3          BATHROOM_NUM    0.002279
12     total_facilities    0.001889
7                   AGE    0.001235
2           BEDROOM_NUM    0.001128
4           BALCONY_NUM    0.000827
8             FLOOR_NUM    0.000513
6               FURNISH    0.000429
13      furnishing_type    0.000365
1         PROPERTY_TYPE    0.000336
11              stories    0.000072
0            PREFERENCE    0.000020

In [24]:
from sklearn.ensemble import GradientBoostingRegressor
gbr = GradientBoostingRegressor(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=3,
    random_state=42
)

gbr.fit(x,y)

GradientBoostingRegressor(learning_rate=0.05, n_estimators=300, random_state=42)

In [25]:
feat_imp2=pd.DataFrame({'feature':x.columns,'importance':gbr.feature_importances_}).sort_values(by='importance',ascending=False)

In [26]:
feat_imp2

                feature  importance
9     SUPERBUILTUP_SQFT    0.556261
5   PRICE_PER_UNIT_AREA    0.435035
3          BATHROOM_NUM    0.004037
10     LOCALITY_WO_CITY    0.003331
2           BEDROOM_NUM    0.000333
1         PROPERTY_TYPE    0.000259
7                   AGE    0.000241
8             FLOOR_NUM    0.000167
12     total_facilities    0.000125
4           BALCONY_NUM    0.000055
13      furnishing_type    0.000054
11              stories    0.000047
0            PREFERENCE    0.000043
6               FURNISH    0.000011

In [28]:

from sklearn.inspection import permutation_importance
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
rf=RandomForestRegressor(n_estimators=300,random_state=42,n_jobs=-1)
rf.fit(x_train,y_train)
perm = permutation_importance(rf, x, y, n_repeats=30, random_state=42, n_jobs=-1)
perm_df = pd.DataFrame({
    'feature': x_train.columns,
    'importance_mean': perm.importances_mean,
}).sort_values(by='importance_mean', ascending=False)

perm_df

                feature  importance_mean
9     SUPERBUILTUP_SQFT         0.816385
5   PRICE_PER_UNIT_AREA         0.790051
10     LOCALITY_WO_CITY         0.010553
3          BATHROOM_NUM         0.007748
12     total_facilities         0.001796
2           BEDROOM_NUM         0.001685
7                   AGE         0.001173
4           BALCONY_NUM         0.000974
6               FURNISH         0.000482
8             FLOOR_NUM         0.000365
1         PROPERTY_TYPE         0.000249
13      furnishing_type         0.000236
11              stories         0.000025
0            PREFERENCE         0.000006

In [29]:

from sklearn.feature_selection import RFE

rf = RandomForestRegressor(n_estimators=300,random_state=42,n_jobs=-1)

rfe = RFE(estimator=rf,n_features_to_select=x.shape[1],step=1)
select_label=rfe.fit(x,y)
selected_features = x.columns[rfe.support_]
selected_coff=select_label.estimator_.feature_importances_

rfe_ranking = pd.DataFrame({
    'feature': x.columns,
    'selected_coff': selected_coff
}).sort_values(by='selected_coff',ascending=False)

rfe_ranking

                feature  selected_coff
9     SUPERBUILTUP_SQFT       0.568941
5   PRICE_PER_UNIT_AREA       0.416581
10     LOCALITY_WO_CITY       0.005648
3          BATHROOM_NUM       0.002017
12     total_facilities       0.001878
7                   AGE       0.001181
2           BEDROOM_NUM       0.001172
4           BALCONY_NUM       0.000827
8             FLOOR_NUM       0.000498
6               FURNISH       0.000449
1         PROPERTY_TYPE       0.000373
13      furnishing_type       0.000315
11              stories       0.000103
0            PREFERENCE       0.000017

In [30]:
import shap
rf = RandomForestRegressor(
    n_estimators=100,
    random_state=42,
    n_jobs=-1
)
rf.fit(x,y)

RandomForestRegressor(n_jobs=-1, random_state=42)

In [31]:
explainer = shap.TreeExplainer(rf)
shap_values = explainer.shap_values(x)
shap_importance = pd.DataFrame({
    'feature': x.columns,
    'mean_abs_shap': np.abs(shap_values).mean(axis=0)
}).sort_values(by='mean_abs_shap', ascending=False)

shap_importance

                feature  mean_abs_shap
9     SUPERBUILTUP_SQFT       0.971980
5   PRICE_PER_UNIT_AREA       0.824243
10     LOCALITY_WO_CITY       0.036866
3          BATHROOM_NUM       0.012094
2           BEDROOM_NUM       0.007095
12     total_facilities       0.006937
7                   AGE       0.005027
4           BALCONY_NUM       0.004107
6               FURNISH       0.002684
1         PROPERTY_TYPE       0.002161
8             FLOOR_NUM       0.002029
13      furnishing_type       0.001842
11              stories       0.000632
0            PREFERENCE       0.000136

In [32]:
rel=corr1.merge(feat_imp,on='feature').merge(feat_imp2,on='feature').merge(perm_df,on='feature').merge(rfe_ranking,on='feature').merge(shap_importance,on='feature')

In [33]:
from sklearn.preprocessing import MinMaxScaler
mn=MinMaxScaler()
col=[ 'correlation', 'importance_x', 'importance_y','importance_mean', 'selected_coff', 'mean_abs_shap']
rel_copy=rel.copy()
rel_copy[col]=mn.fit_transform(rel_copy[col])

In [34]:
rel_copy

,feature,correlation,importance_x,importance_y,importance_mean,selected_coff,mean_abs_shap
0,SUPERBUILTUP_SQFT,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
1,PRICE_PER_UNIT_AREA,0.987005,0.733118,0.782066,0.967744,0.732196,0.847982
2,BATHROOM_NUM,0.837035,0.003973,0.007237,0.009483,0.003515,0.012304
3,BEDROOM_NUM,0.771889,0.001950,0.000579,0.002057,0.002030,0.007161
4,BALCONY_NUM,0.454141,0.001419,0.000078,0.001186,0.001422,0.004086
5,total_facilities,0.326715,0.003288,0.000205,0.002192,0.003270,0.006998
6,PREFERENCE,0.259526,0.000000,0.000057,0.000000,0.000000,0.000000
7,AGE,0.249092,0.002138,0.000413,0.001430,0.002045,0.005032
8,furnishing_type,0.188871,0.000607,0.000076,0.000282,0.000524,0.001755
9,FLOOR_NUM,0.144730,0.000867,0.000280,0.000440,0.000844,0.001948
10,FURNISH,0.098566,0.000720,0.000000,0.000583,0.000758,0.002622
11,PROPERTY_TYPE,0.085078,0.000557,0.000444,0.000298,0.000625,0.002083
12,LOCALITY_WO_CITY,0.034118,0.009830,0.005968,0.012919,0.009897,0.037793
13,stories,0.000000,0.000091,0.000064,0.000024,0.000150,0.000510

In [35]:
rel_copy['importance_row_mean'] = rel_copy[
    ['correlation','importance_x', 'importance_y', 'importance_mean','selected_coff', 'mean_abs_shap']
].mean(axis=1)

In [36]:
rel_copy

,feature,correlation,importance_x,importance_y,importance_mean,selected_coff,mean_abs_shap,importance_row_mean
0,SUPERBUILTUP_SQFT,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
1,PRICE_PER_UNIT_AREA,0.987005,0.733118,0.782066,0.967744,0.732196,0.847982,0.841685
2,BATHROOM_NUM,0.837035,0.003973,0.007237,0.009483,0.003515,0.012304,0.145591
3,BEDROOM_NUM,0.771889,0.001950,0.000579,0.002057,0.002030,0.007161,0.130944
4,BALCONY_NUM,0.454141,0.001419,0.000078,0.001186,0.001422,0.004086,0.077055
5,total_facilities,0.326715,0.003288,0.000205,0.002192,0.003270,0.006998,0.057111
6,PREFERENCE,0.259526,0.000000,0.000057,0.000000,0.000000,0.000000,0.043264
7,AGE,0.249092,0.002138,0.000413,0.001430,0.002045,0.005032,0.043358
8,furnishing_type,0.188871,0.000607,0.000076,0.000282,0.000524,0.001755,0.032019
9,FLOOR_NUM,0.144730,0.000867,0.000280,0.000440,0.000844,0.001948,0.024851
10,FURNISH,0.098566,0.000720,0.000000,0.000583,0.000758,0.002622,0.017208
11,PROPERTY_TYPE,0.085078,0.000557,0.000444,0.000298,0.000625,0.002083,0.014847
12,LOCALITY_WO_CITY,0.034118,0.009830,0.005968,0.012919,0.009897,0.037793,0.018421
13,stories,0.000000,0.000091,0.000064,0.000024,0.000150,0.000510,0.000140

In [37]:
rel_copy.drop(['correlation','importance_x', 'importance_y', 'importance_mean','selected_coff', 'mean_abs_shap'],axis=1,inplace=True)

In [38]:
rel_copy.sort_values(by='importance_row_mean',ascending=False)

                feature  importance_row_mean
0     SUPERBUILTUP_SQFT             1.000000
1   PRICE_PER_UNIT_AREA             0.841685
2          BATHROOM_NUM             0.145591
3           BEDROOM_NUM             0.130944
4           BALCONY_NUM             0.077055
5      total_facilities             0.057111
7                   AGE             0.043358
6            PREFERENCE             0.043264
8       furnishing_type             0.032019
9             FLOOR_NUM             0.024851
12     LOCALITY_WO_CITY             0.018421
10              FURNISH             0.017208
11        PROPERTY_TYPE             0.014847
13              stories             0.000140

In [39]:
from sklearn.model_selection import cross_val_score
rf=RandomForestRegressor(n_estimators=300,random_state=42,n_jobs=-1)
scores=cross_val_score(rf,x,y,scoring='r2',cv=10)

In [40]:
scores.mean()

np.float64(0.9782896747397188)

In [41]:
rf=RandomForestRegressor(n_estimators=300,random_state=42,n_jobs=-1)
scores=cross_val_score(rf,x.drop(['stories','PROPERTY_TYPE'],axis=1),y,scoring='r2',cv=10)
scores.mean()

np.float64(0.9782577776656514)

In [42]:
rf=RandomForestRegressor(n_estimators=300,random_state=42,n_jobs=-1)
scores=cross_val_score(rf,x.drop(['stories','PREFERENCE'],axis=1),y,scoring='r2',cv=10)
scores.mean()

np.float64(0.9783615742084353)

In [44]:
rf=RandomForestRegressor(n_estimators=300,random_state=42,n_jobs=-1)
scores=cross_val_score(rf,x.drop(['stories','PREFERENCE','FURNISH'],axis=1),y,scoring='r2',cv=10)
scores.mean()

np.float64(0.9783990422296057)

In [45]:
rf=RandomForestRegressor(n_estimators=300,random_state=42,n_jobs=-1)
scores=cross_val_score(rf,x.drop(['stories','PREFERENCE','PROPERTY_TYPE','FLOOR_NUM'],axis=1),y,scoring='r2',cv=10)
scores.mean()

np.float64(0.978300532498567)

In [47]:
rf=RandomForestRegressor(n_estimators=300,random_state=42,n_jobs=-1)
scores=cross_val_score(rf,x.drop(['stories','PREFERENCE','FURNISH','FLOOR_NUM','PROPERTY_TYPE'],axis=1),y,scoring='r2',cv=10)
scores.mean()

np.float64(0.9784802265994399)

In [48]:
rf=RandomForestRegressor(n_estimators=300,random_state=42,n_jobs=-1)
scores=cross_val_score(rf,x.drop(['stories','PREFERENCE','FURNISH','FLOOR_NUM'],axis=1),y,scoring='r2',cv=10)
scores.mean()

np.float64(0.9784802265994399)

In [49]:
export_df=df.drop(['stories','PREFERENCE','PROPERTY_TYPE','FURNISH','FLOOR_NUM'],axis=1)

In [50]:
df.head(3)

,PREFERENCE,PROPERTY_TYPE,BEDROOM_NUM,BATHROOM_NUM,BALCONY_NUM,PRICE_PER_UNIT_AREA,FURNISH,AGE,FLOOR_NUM,SUPERBUILTUP_SQFT,PRICE,LOCALITY_WO_CITY,stories,total_facilities,furnishing_type
0,S,Residential Apartment,4.0,4.0,4.0,8766.0,Semi-furnished,5-10,high,3434.0,2.63,Sector 84,single,4,0
1,S,Residential Apartment,4.0,4.0,3.0,21176.0,Semi-furnished,1-5,mid,2870.0,3.60,Sector 81,single,5,0
2,S,Residential Apartment,3.0,3.0,3.0,13740.0,Semi-furnished,1-5,high,2802.0,3.85,Sector 112,single,4,0

In [51]:
export_df.to_csv("model_trainer.csv")